name: rolling_ball_example
description: An example ball game.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dart_sdl: ^0.4.0
  dart_synthizer: ^0.0.4
  json_annotation: ^4.1.0
  ziggurat: ^0.13.0
  ziggurat_sounds: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^5.0.0
  pedantic: ^1.11.1
  test: ^1.17.11
